#!/usr/bin/env bash
# Expects test.c in top level

BASE_DIR="/autograder"
FROM="/autograder/submission"
TO="/autograder/source"
SRC="/autograder/source/src"
RESULTS_DEST="/autograder/results/results.json"

mkdir -p "$SRC"
cp "${FROM}/paging.c" "$SRC"

# gcc test.c readFile.c "paging.c" -o student_program
cd "$SRC" || echo "Failed to cd into ${SRC}"
gcc -std=gnu99 test.c -o student_program

# Run the autograder code
./student_program > "$RESULTS_DEST"
