#!/usr/bin/env bash
# Expects test.c in top level

BASE_DIR="/autograder"
FROM="/autograder/submission"
TO="/autograder/source"
SRC="/autograder/source/src"
RESULTS_DEST="/autograder/results/results.json"

mkdir -p "$SRC"
cp "${FROM}/paging.c" "$SRC"

cd "$SRC" || echo "Failed to cd into ${SRC}"
gcc -std=gnu99 test.c paging.c readFile.c -o student_program -lm

# Run the autograder code
./student_program 
